### PR TITLE
Remove description on hash generation

### PR DESCRIPTION
**Pull request by wiliansilvazup**
Signed-off-by: Wilian Gabriel <wilian.silva@zup.com.br>

### CODE REVIEW

**Comment by iancardosozup** [comment]
i think we should remove "CommitEmail" from hash too, i think the hash should be based on file attributes

**Comment by wiliansilvazup** [comment]
> i think we should remove "CommitEmail" from hash too, i think the hash should be based on file attributes

`commitEmail` I don't think it's possible. Because think with me.
You have a "hello world" in repository X. And I have a "hello world" in repository Y. Both sent to Horusec-Platform. Great how these projects are equals and vulnerabilities too we have only one hash. 
Now imagine you change your "hello world" to an "API", your vulnerability not exist more. And me changed my "hello world" added some an `print()` my code continue vulnerable.
And when you run your security workflow is vulnerable too because my changes.

! Because this is not possible, this context is possible apply to all export format in Horusec-CLI not only Horusec-API !

**Comment by matheusalcantarazup** [comment]
> 

But we will have different file paths which will generate different vulnerability hashes, right?

**Comment by nathanmartinszup** [comment]
> i think we should remove "CommitEmail" from hash too, i think the hash should be based on file attributes

This [issue](https://github.com/ZupIT/horusec/issues/973) contains a problem related to this. For some reason two different emails were found for the same vulnerability, I'll take a deeper look now.

**Comment by wiliansilvazup** [comment]
> > > i think we should remove "CommitEmail" from hash too, i think the hash should be based on file attributes
> > 
> > 
> > `commitEmail` I don't think it's possible. Because think with me. You have a "hello world" in repository X. And I have a "hello world" in repository Y. Both sent to Horusec-Platform. Great how these projects are equals and vulnerabilities too we have only one hash. Now imagine you change your "hello world" to an "API", your vulnerability not exist more. And me changed my "hello world" added some an `print()` my code continue vulnerable. And when you run your security workflow is vulnerable too because my changes.
> > ! Because this is not possible, this context is possible apply to all export format in Horusec-CLI not only Horusec-API !
> 
> But we will have different file paths which will generate different vulnerability hashes, right?

not always, because it can be in `main` of the project that both are in the same path.
But I'm thinking `commitEmail` by default is not enable in horusec-cli, when enabled is a differential to separate the vulnerabilities and this is bad because all hashes can be changed

**Comment by wiliansilvazup** [comment]
Maybe when semantic analysis it's stable. We can use to validate inside of the code using comments.
- Single line
- Single function
- Single file
And deprecating the hash by language slowly

**Comment by iancardosozup** [comment]
> not always, because it can be in `main` of the project that both are in the same path. But I'm thinking `commitEmail` by default is not enable in horusec-cli, when enabled is a differential to separate the vulnerabilities and this is bad because all hashes can be changed

i'd prefer some duplicate vulnerabilities (we can still find this bug and treat it) than 100% duplicates vulnerabilities when commit-authors is enabled. I think hashes changing when we add more information to analysis make no sense

**Comment by wiliansilvazup** [comment]
> > not always, because it can be in `main` of the project that both are in the same path. But I'm thinking `commitEmail` by default is not enable in horusec-cli, when enabled is a differential to separate the vulnerabilities and this is bad because all hashes can be changed
> 
> i'd prefer some duplicate vulnerabilities (we can still find this bug and treat it) than 100% duplicates vulnerabilities when commit-authors is enabled. I think hashes changing when we add more information to analysis make no sense

yeah ... maybe is better remove commitEmail too.

**Comment by matheusalcantarazup** [comment]
> But guys how we keep old versions of the hash without save older state of the `description` and `commitEmail` ? @matheusalcantarazup @iancardosozup @nathanmartinszup

I think that we follow the same idea proposed here; we generate a hash using the email and description and put this hash inside `OldHashes` and them generate a new hash without these fields.

**Comment by iancardosozup** [comment]
we'll have 2 description fields, oldOne and newOne, we'll generate the hashes needed using one in some specific scenario until the deadline, then we delete the oldOne from the struct.

**Comment by wiliansilvazup** [comment]
> we'll have 2 description fields, oldOne and newOne, we'll generate the hashes needed using one in some specific scenario until the deadline, then we delete the oldOne from the struct.

About v it's looking like the item that was considered in our adr [Keep the old format statically](https://github.com/ZupIT/horusec-adr/pull/2/files#diff-78658a5906b3bd2eae17502ea16f859b350907f9d2c7a23f0aae7b98e044c458R54) and we discussed not to choose this format, now is it necessary ? I did not understand

**Pull request merged**
